name: Test

on:
  push:
  pull_request:

env:
  JAVA_DIST: 'zulu'
  JAVA_VERSION: 22

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Compile and Test with JVM Flags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm_flags:
          - "-XX:+AggressiveOpts"
          - "-XX:+AlwaysPreTouch"
          - "-XX:+DisableExplicitGC"
          - "-XX:+OptimizeStringConcat"
          - "-XX:+UseAdaptiveSizePolicy"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Debug MAVEN_OPTS
        run: |
          echo "Running with JVM flags: ${{ matrix.jvm_flags }}"
      - name: Build and Test with Maven
        env:
          MAVEN_OPTS: ${{ matrix.jvm_flags }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" \
          mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage || exit 1
      - name: Get JaCoCo Coverage
        id: coverage  
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
          echo "COVERAGE=$coverage" >> $GITHUB_ENV
      - name: Fail if coverage has not improved.
        run: |
          coverage=$COVERAGE
          threshold=13.43
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage has not improved."
            exit 1
          else
            echo "New coverage: $coverage%"
          fi
